import { exadevConfig } from "@exadev/eslint-config";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import globals from "globals";

// Lints the workspace root's own files -- its TypeScript tooling configs and its prose and data -- and nothing else.
//
// packages/** stays ignored here. The package keeps its own eslint.config.ts, because file scoping, tsconfig wiring, and the isomorphism import bans are genuinely per-package concerns; a root run that also walked the package would apply this program's tsconfig to source files it does not contain.
export default exadevConfig(
  {},
  {
    ignores: [
      "packages/**",
      "node_modules",
      ".turbo",
      "coverage",
      // Generated by semantic-release from commit messages; nothing about its formatting is a human decision, and the same goes for the lockfile.
      "CHANGELOG.md",
      "pnpm-lock.yaml",
    ],
  },
  {
    languageOptions: {
      parserOptions: {
        project: ["./tsconfig.json"],
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node },
    },
  },
  {
    rules: {
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
    },
  },
  eslintPluginPrettierRecommended,
);
